Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.hostsupdater.aliases = ["development.local"]
  # Sync folder from OS to VM
                       # "." means current location -  into/inside VM
  config.vm.synced_folder ".", "/home/vagrant/app"

  # run the provisioning script to install the dependencies and run the app
  config.vm.provision "shell", path: "./provision.sh"          
 
end
